# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 04:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='join',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='traveller',
        ),
        migrations.DeleteModel(
            name='Join',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
